# Generated by Django 5.2.1 on 2025-05-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('done', 'Done'), ('postponed', 'Postponed')], default='ongoing', max_length=20),
        ),
    ]
