# Generated by Django 5.2.1 on 2025-05-21 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
    ]
